global using FluentValidation;
global using FluentValidation.AspNetCore;
global using Library.Application;
global using Microsoft.AspNetCore.Mvc;
global using Library.Application.Features.Identity.Requests.SignUp;
global using Library.Domain.Common.Results;
global using MediatR;
global using Library.Application.Common.Interfaces;
global using System.Security.Claims;
global using Library.Api.Services;
global using Library.Api.Requests;
global using Library.Application.Features.Books.Commands.CreateBooks;
global using Library.Application.Features.Books.Queries.GetBook;
global using Library.Domain.Common.Constants;
global using Library.Application.Features.UploadedFiles.Queries.GetFileQuerys;
global using Library.Application.Features.Identity.Dtos;
global using Library.Application.Features.Identity.Queries.SignIn;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Library.Api;
global using Library.Infrastructure;
global using Library.Infrastructure.Data;
global using Library.Application.Features.BorrowingRecords.Commands.CreateBorrowingRecords;
global using Library.Application.Features.BorrowingRecords.Queries.GetBorrowingRecord;
global using Library.Application.Features.BorrowingRecords.Dtos;
global using Microsoft.AspNetCore.Authorization;
namespace Library.Api.Global;

